backend.py:890:SB
--------------------------------------------------------------------
Last Page: https://haveibeenpwned.com/
 Duration: 6.24s
  Browser: Chrome 132.0.6834.196 / headless
   Driver: chromedriver 132.0.6834.159
Timestamp: 1739107482  (Unix Timestamp)
     Date: Sunday, 9 February 2025
     Time: 1:24:42 PM  (GMT Summer Time, UTC+01:00)
--------------------------------------------------------------------
Traceback:
  Traceback (most recent call last):
  File "C:\Users\Admin\OneDrive\Dokumente\OSINT\backend.py", line 15, in _haveibeenpwned
    sb.uc_gui_click_captcha()
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\seleniumbase\core\browser_launcher.py", line 5361, in <lambda>
    lambda *args, **kwargs: uc_gui_click_captcha(
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\seleniumbase\core\browser_launcher.py", line 1431, in uc_gui_click_captcha
    _uc_gui_click_captcha(
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\seleniumbase\core\browser_launcher.py", line 1143, in _uc_gui_click_captcha
    install_pyautogui_if_missing(driver)
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\seleniumbase\core\browser_launcher.py", line 904, in install_pyautogui_if_missing
    verify_pyautogui_has_a_headed_browser(driver)
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\seleniumbase\core\browser_launcher.py", line 832, in verify_pyautogui_has_a_headed_browser
    raise Exception(
Exception: PyAutoGUI can't be used in headless mode!
